# Generated by Django 5.0 on 2024-01-30 21:46

import django.contrib.postgres.fields
import user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_file'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='faces'),
        ),
    ]
